name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: corepack enable

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm run type-check

      - run: pnpm run lint

      - run: pnpm test

      - run: pnpm build